RestClients:
  #Amazon Lex is a service for building conversational interfaces into any application using voice and text. 
  #Amazon Lex provides the advanced deep learning functionalities of automatic speech recognition (ASR)
  #for converting speech to text, and natural language understanding (NLU) to recognize the intent of the text, 
  #to enable you to build applications with highly engaging user experiences and lifelike conversational interactions. 
  #With Amazon Lex, the same deep learning technologies that power Amazon Alexa are now available 
  #to any developer, enabling you to quickly and easily build sophisticated, natural language, conversational bots (“chatbots”).
  Amazon Lex (Amazon Lex Runtime V2):
    UUID: 13f7783c-cd64-4625-a663-82b504bd4195
    Url: https://runtime-v2-lex.eu-central-1.amazonaws.com
    Icon: res:/webContent/icons/AmazonLex.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.connector.aws.authentication.Aws4AuthenticationFeature
    Properties:
      serviceName: lex
