/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.ActiveContextParametersMap;
import com.amazonaws.lex.runtime.v2.ActiveContextTimeToLive;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * &lt;p&gt;Contains information about the contexts that a user is using in a session. You can configure Amazon Lex V2 to set a context when an intent is fulfilled, or you can set a context using the , , or operations.&lt;/p&gt; &lt;p&gt;Use a context to indicate to Amazon Lex V2 intents that should be used as follow-up intents. For example, if the active context is &lt;code&gt;order-fulfilled&lt;/code&gt;, only intents that have &lt;code&gt;order-fulfilled&lt;/code&gt; configured as a trigger are considered for follow up.&lt;/p&gt;
 */
@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class ActiveContext {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("timeToLive")
  private ActiveContextTimeToLive timeToLive = null;

  @JsonProperty("contextAttributes")
  private ActiveContextParametersMap contextAttributes = null;

  public ActiveContext name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActiveContext timeToLive(ActiveContextTimeToLive timeToLive) {
    this.timeToLive = timeToLive;
    return this;
  }

   /**
   * Get timeToLive
   * @return timeToLive
  **/
  public ActiveContextTimeToLive getTimeToLive() {
    return timeToLive;
  }

  public void setTimeToLive(ActiveContextTimeToLive timeToLive) {
    this.timeToLive = timeToLive;
  }

  public ActiveContext contextAttributes(ActiveContextParametersMap contextAttributes) {
    this.contextAttributes = contextAttributes;
    return this;
  }

   /**
   * Get contextAttributes
   * @return contextAttributes
  **/
  public ActiveContextParametersMap getContextAttributes() {
    return contextAttributes;
  }

  public void setContextAttributes(ActiveContextParametersMap contextAttributes) {
    this.contextAttributes = contextAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiveContext activeContext = (ActiveContext) o;
    return Objects.equals(this.name, activeContext.name) &&
        Objects.equals(this.timeToLive, activeContext.timeToLive) &&
        Objects.equals(this.contextAttributes, activeContext.contextAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, timeToLive, contextAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiveContext {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    timeToLive: ").append(toIndentedString(timeToLive)).append("\n");
    sb.append("    contextAttributes: ").append(toIndentedString(contextAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
