/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The time that a context is active. You can specify the time to live in seconds or in conversation turns.
 */
@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class ActiveContextTimeToLive {
  @JsonProperty("timeToLiveInSeconds")
  private Integer timeToLiveInSeconds = null;

  @JsonProperty("turnsToLive")
  private Integer turnsToLive = null;

  public ActiveContextTimeToLive timeToLiveInSeconds(Integer timeToLiveInSeconds) {
    this.timeToLiveInSeconds = timeToLiveInSeconds;
    return this;
  }

   /**
   * Get timeToLiveInSeconds
   * @return timeToLiveInSeconds
  **/
  public Integer getTimeToLiveInSeconds() {
    return timeToLiveInSeconds;
  }

  public void setTimeToLiveInSeconds(Integer timeToLiveInSeconds) {
    this.timeToLiveInSeconds = timeToLiveInSeconds;
  }

  public ActiveContextTimeToLive turnsToLive(Integer turnsToLive) {
    this.turnsToLive = turnsToLive;
    return this;
  }

   /**
   * Get turnsToLive
   * @return turnsToLive
  **/
  public Integer getTurnsToLive() {
    return turnsToLive;
  }

  public void setTurnsToLive(Integer turnsToLive) {
    this.turnsToLive = turnsToLive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiveContextTimeToLive activeContextTimeToLive = (ActiveContextTimeToLive) o;
    return Objects.equals(this.timeToLiveInSeconds, activeContextTimeToLive.timeToLiveInSeconds) &&
        Objects.equals(this.turnsToLive, activeContextTimeToLive.turnsToLive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeToLiveInSeconds, turnsToLive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiveContextTimeToLive {\n");
    
    sb.append("    timeToLiveInSeconds: ").append(toIndentedString(timeToLiveInSeconds)).append("\n");
    sb.append("    turnsToLive: ").append(toIndentedString(turnsToLive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
