/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DeleteSessionResponse
 */

@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class DeleteSessionResponse {
  @JsonProperty("botId")
  private String botId = null;

  @JsonProperty("botAliasId")
  private String botAliasId = null;

  @JsonProperty("localeId")
  private String localeId = null;

  @JsonProperty("sessionId")
  private String sessionId = null;

  public DeleteSessionResponse botId(String botId) {
    this.botId = botId;
    return this;
  }

   /**
   * Get botId
   * @return botId
  **/
  public String getBotId() {
    return botId;
  }

  public void setBotId(String botId) {
    this.botId = botId;
  }

  public DeleteSessionResponse botAliasId(String botAliasId) {
    this.botAliasId = botAliasId;
    return this;
  }

   /**
   * Get botAliasId
   * @return botAliasId
  **/
  public String getBotAliasId() {
    return botAliasId;
  }

  public void setBotAliasId(String botAliasId) {
    this.botAliasId = botAliasId;
  }

  public DeleteSessionResponse localeId(String localeId) {
    this.localeId = localeId;
    return this;
  }

   /**
   * Get localeId
   * @return localeId
  **/
  public String getLocaleId() {
    return localeId;
  }

  public void setLocaleId(String localeId) {
    this.localeId = localeId;
  }

  public DeleteSessionResponse sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteSessionResponse deleteSessionResponse = (DeleteSessionResponse) o;
    return Objects.equals(this.botId, deleteSessionResponse.botId) &&
        Objects.equals(this.botAliasId, deleteSessionResponse.botAliasId) &&
        Objects.equals(this.localeId, deleteSessionResponse.localeId) &&
        Objects.equals(this.sessionId, deleteSessionResponse.sessionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(botId, botAliasId, localeId, sessionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteSessionResponse {\n");
    
    sb.append("    botId: ").append(toIndentedString(botId)).append("\n");
    sb.append("    botAliasId: ").append(toIndentedString(botAliasId)).append("\n");
    sb.append("    localeId: ").append(toIndentedString(localeId)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
