/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.DialogActionType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The next action that Amazon Lex V2 should take.
 */
@jakarta.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class DialogAction {
  @JsonProperty("type")
  private DialogActionType type = null;

  @JsonProperty("slotToElicit")
  private String slotToElicit = null;

  public DialogAction type(DialogActionType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public DialogActionType getType() {
    return type;
  }

  public void setType(DialogActionType type) {
    this.type = type;
  }

  public DialogAction slotToElicit(String slotToElicit) {
    this.slotToElicit = slotToElicit;
    return this;
  }

   /**
   * Get slotToElicit
   * @return slotToElicit
  **/
  public String getSlotToElicit() {
    return slotToElicit;
  }

  public void setSlotToElicit(String slotToElicit) {
    this.slotToElicit = slotToElicit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DialogAction dialogAction = (DialogAction) o;
    return Objects.equals(this.type, dialogAction.type) &&
        Objects.equals(this.slotToElicit, dialogAction.slotToElicit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, slotToElicit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DialogAction {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    slotToElicit: ").append(toIndentedString(slotToElicit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
