/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.ConfidenceScore;
import com.amazonaws.lex.runtime.v2.Intent;
import com.amazonaws.lex.runtime.v2.SentimentResponse;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An intent that Amazon Lex V2 determined might satisfy the user&#x27;s utterance. The intents are ordered by the confidence score. 
 */
@jakarta.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class Interpretation {
  @JsonProperty("nluConfidence")
  private ConfidenceScore nluConfidence = null;

  @JsonProperty("sentimentResponse")
  private SentimentResponse sentimentResponse = null;

  @JsonProperty("intent")
  private Intent intent = null;

  public Interpretation nluConfidence(ConfidenceScore nluConfidence) {
    this.nluConfidence = nluConfidence;
    return this;
  }

   /**
   * Get nluConfidence
   * @return nluConfidence
  **/
  public ConfidenceScore getNluConfidence() {
    return nluConfidence;
  }

  public void setNluConfidence(ConfidenceScore nluConfidence) {
    this.nluConfidence = nluConfidence;
  }

  public Interpretation sentimentResponse(SentimentResponse sentimentResponse) {
    this.sentimentResponse = sentimentResponse;
    return this;
  }

   /**
   * Get sentimentResponse
   * @return sentimentResponse
  **/
  public SentimentResponse getSentimentResponse() {
    return sentimentResponse;
  }

  public void setSentimentResponse(SentimentResponse sentimentResponse) {
    this.sentimentResponse = sentimentResponse;
  }

  public Interpretation intent(Intent intent) {
    this.intent = intent;
    return this;
  }

   /**
   * Get intent
   * @return intent
  **/
  public Intent getIntent() {
    return intent;
  }

  public void setIntent(Intent intent) {
    this.intent = intent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Interpretation interpretation = (Interpretation) o;
    return Objects.equals(this.nluConfidence, interpretation.nluConfidence) &&
        Objects.equals(this.sentimentResponse, interpretation.sentimentResponse) &&
        Objects.equals(this.intent, interpretation.intent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nluConfidence, sentimentResponse, intent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Interpretation {\n");
    
    sb.append("    nluConfidence: ").append(toIndentedString(nluConfidence)).append("\n");
    sb.append("    sentimentResponse: ").append(toIndentedString(sentimentResponse)).append("\n");
    sb.append("    intent: ").append(toIndentedString(intent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
