/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.ConfirmationState;
import com.amazonaws.lex.runtime.v2.IntentState;
import com.amazonaws.lex.runtime.v2.Slots;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The current intent that Amazon Lex V2 is attempting to fulfill.
 */
@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class Intent {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("slots")
  private Slots slots = null;

  @JsonProperty("state")
  private IntentState state = null;

  @JsonProperty("confirmationState")
  private ConfirmationState confirmationState = null;

  public Intent name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Intent slots(Slots slots) {
    this.slots = slots;
    return this;
  }

   /**
   * Get slots
   * @return slots
  **/
  public Slots getSlots() {
    return slots;
  }

  public void setSlots(Slots slots) {
    this.slots = slots;
  }

  public Intent state(IntentState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public IntentState getState() {
    return state;
  }

  public void setState(IntentState state) {
    this.state = state;
  }

  public Intent confirmationState(ConfirmationState confirmationState) {
    this.confirmationState = confirmationState;
    return this;
  }

   /**
   * Get confirmationState
   * @return confirmationState
  **/
  public ConfirmationState getConfirmationState() {
    return confirmationState;
  }

  public void setConfirmationState(ConfirmationState confirmationState) {
    this.confirmationState = confirmationState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Intent intent = (Intent) o;
    return Objects.equals(this.name, intent.name) &&
        Objects.equals(this.slots, intent.slots) &&
        Objects.equals(this.state, intent.state) &&
        Objects.equals(this.confirmationState, intent.confirmationState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, slots, state, confirmationState);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Intent {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slots: ").append(toIndentedString(slots)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    confirmationState: ").append(toIndentedString(confirmationState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
