/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.ImageResponseCard;
import com.amazonaws.lex.runtime.v2.MessageContentType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Container for text that is returned to the customer..
 */
@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class Message {
  @JsonProperty("content")
  private String content = null;

  @JsonProperty("contentType")
  private MessageContentType contentType = null;

  @JsonProperty("imageResponseCard")
  private ImageResponseCard imageResponseCard = null;

  public Message content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Message contentType(MessageContentType contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  public MessageContentType getContentType() {
    return contentType;
  }

  public void setContentType(MessageContentType contentType) {
    this.contentType = contentType;
  }

  public Message imageResponseCard(ImageResponseCard imageResponseCard) {
    this.imageResponseCard = imageResponseCard;
    return this;
  }

   /**
   * Get imageResponseCard
   * @return imageResponseCard
  **/
  public ImageResponseCard getImageResponseCard() {
    return imageResponseCard;
  }

  public void setImageResponseCard(ImageResponseCard imageResponseCard) {
    this.imageResponseCard = imageResponseCard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.content, message.content) &&
        Objects.equals(this.contentType, message.contentType) &&
        Objects.equals(this.imageResponseCard, message.imageResponseCard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, contentType, imageResponseCard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    imageResponseCard: ").append(toIndentedString(imageResponseCard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
