/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets MessageContentType
 */
public enum MessageContentType {
  CUSTOMPAYLOAD("CustomPayload"),
  IMAGERESPONSECARD("ImageResponseCard"),
  PLAINTEXT("PlainText"),
  SSML("SSML");

  private String value;

  MessageContentType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MessageContentType fromValue(String text) {
    for (MessageContentType b : MessageContentType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
