/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PutSessionResponse
 */

@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class PutSessionResponse {
  @JsonProperty("audioStream")
  private String audioStream = null;

  public PutSessionResponse audioStream(String audioStream) {
    this.audioStream = audioStream;
    return this;
  }

   /**
   * Get audioStream
   * @return audioStream
  **/
  public String getAudioStream() {
    return audioStream;
  }

  public void setAudioStream(String audioStream) {
    this.audioStream = audioStream;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutSessionResponse putSessionResponse = (PutSessionResponse) o;
    return Objects.equals(this.audioStream, putSessionResponse.audioStream);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audioStream);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutSessionResponse {\n");
    
    sb.append("    audioStream: ").append(toIndentedString(audioStream)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
