/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.Messages;
import com.amazonaws.lex.runtime.v2.SessionState;
import com.amazonaws.lex.runtime.v2.StringMap;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PutSessionRequest
 */

@jakarta.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class PutSessionRequest {
  @JsonProperty("messages")
  private Messages messages = null;

  @JsonProperty("sessionState")
  private SessionState sessionState = null;

  @JsonProperty("requestAttributes")
  private StringMap requestAttributes = null;

  public PutSessionRequest messages(Messages messages) {
    this.messages = messages;
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  public Messages getMessages() {
    return messages;
  }

  public void setMessages(Messages messages) {
    this.messages = messages;
  }

  public PutSessionRequest sessionState(SessionState sessionState) {
    this.sessionState = sessionState;
    return this;
  }

   /**
   * Get sessionState
   * @return sessionState
  **/
  public SessionState getSessionState() {
    return sessionState;
  }

  public void setSessionState(SessionState sessionState) {
    this.sessionState = sessionState;
  }

  public PutSessionRequest requestAttributes(StringMap requestAttributes) {
    this.requestAttributes = requestAttributes;
    return this;
  }

   /**
   * Get requestAttributes
   * @return requestAttributes
  **/
  public StringMap getRequestAttributes() {
    return requestAttributes;
  }

  public void setRequestAttributes(StringMap requestAttributes) {
    this.requestAttributes = requestAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutSessionRequest putSessionRequest = (PutSessionRequest) o;
    return Objects.equals(this.messages, putSessionRequest.messages) &&
        Objects.equals(this.sessionState, putSessionRequest.sessionState) &&
        Objects.equals(this.requestAttributes, putSessionRequest.requestAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, sessionState, requestAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutSessionRequest {\n");
    
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    sessionState: ").append(toIndentedString(sessionState)).append("\n");
    sb.append("    requestAttributes: ").append(toIndentedString(requestAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
