/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.SessionState;
import com.amazonaws.lex.runtime.v2.StringMap;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RecognizeTextRequest
 */

@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class RecognizeTextRequest {
  @JsonProperty("text")
  private String text = null;

  @JsonProperty("sessionState")
  private SessionState sessionState = null;

  @JsonProperty("requestAttributes")
  private StringMap requestAttributes = null;

  public RecognizeTextRequest text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public RecognizeTextRequest sessionState(SessionState sessionState) {
    this.sessionState = sessionState;
    return this;
  }

   /**
   * Get sessionState
   * @return sessionState
  **/
  public SessionState getSessionState() {
    return sessionState;
  }

  public void setSessionState(SessionState sessionState) {
    this.sessionState = sessionState;
  }

  public RecognizeTextRequest requestAttributes(StringMap requestAttributes) {
    this.requestAttributes = requestAttributes;
    return this;
  }

   /**
   * Get requestAttributes
   * @return requestAttributes
  **/
  public StringMap getRequestAttributes() {
    return requestAttributes;
  }

  public void setRequestAttributes(StringMap requestAttributes) {
    this.requestAttributes = requestAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecognizeTextRequest recognizeTextRequest = (RecognizeTextRequest) o;
    return Objects.equals(this.text, recognizeTextRequest.text) &&
        Objects.equals(this.sessionState, recognizeTextRequest.sessionState) &&
        Objects.equals(this.requestAttributes, recognizeTextRequest.requestAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, sessionState, requestAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecognizeTextRequest {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    sessionState: ").append(toIndentedString(sessionState)).append("\n");
    sb.append("    requestAttributes: ").append(toIndentedString(requestAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
