/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.Interpretations;
import com.amazonaws.lex.runtime.v2.Messages;
import com.amazonaws.lex.runtime.v2.SessionState;
import com.amazonaws.lex.runtime.v2.StringMap;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RecognizeTextResponse
 */

@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class RecognizeTextResponse {
  @JsonProperty("messages")
  private Messages messages = null;

  @JsonProperty("sessionState")
  private SessionState sessionState = null;

  @JsonProperty("interpretations")
  private Interpretations interpretations = null;

  @JsonProperty("requestAttributes")
  private StringMap requestAttributes = null;

  @JsonProperty("sessionId")
  private String sessionId = null;

  public RecognizeTextResponse messages(Messages messages) {
    this.messages = messages;
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  public Messages getMessages() {
    return messages;
  }

  public void setMessages(Messages messages) {
    this.messages = messages;
  }

  public RecognizeTextResponse sessionState(SessionState sessionState) {
    this.sessionState = sessionState;
    return this;
  }

   /**
   * Get sessionState
   * @return sessionState
  **/
  public SessionState getSessionState() {
    return sessionState;
  }

  public void setSessionState(SessionState sessionState) {
    this.sessionState = sessionState;
  }

  public RecognizeTextResponse interpretations(Interpretations interpretations) {
    this.interpretations = interpretations;
    return this;
  }

   /**
   * Get interpretations
   * @return interpretations
  **/
  public Interpretations getInterpretations() {
    return interpretations;
  }

  public void setInterpretations(Interpretations interpretations) {
    this.interpretations = interpretations;
  }

  public RecognizeTextResponse requestAttributes(StringMap requestAttributes) {
    this.requestAttributes = requestAttributes;
    return this;
  }

   /**
   * Get requestAttributes
   * @return requestAttributes
  **/
  public StringMap getRequestAttributes() {
    return requestAttributes;
  }

  public void setRequestAttributes(StringMap requestAttributes) {
    this.requestAttributes = requestAttributes;
  }

  public RecognizeTextResponse sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecognizeTextResponse recognizeTextResponse = (RecognizeTextResponse) o;
    return Objects.equals(this.messages, recognizeTextResponse.messages) &&
        Objects.equals(this.sessionState, recognizeTextResponse.sessionState) &&
        Objects.equals(this.interpretations, recognizeTextResponse.interpretations) &&
        Objects.equals(this.requestAttributes, recognizeTextResponse.requestAttributes) &&
        Objects.equals(this.sessionId, recognizeTextResponse.sessionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, sessionState, interpretations, requestAttributes, sessionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecognizeTextResponse {\n");
    
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    sessionState: ").append(toIndentedString(sessionState)).append("\n");
    sb.append("    interpretations: ").append(toIndentedString(interpretations)).append("\n");
    sb.append("    requestAttributes: ").append(toIndentedString(requestAttributes)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
