/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The individual sentiment responses for the utterance.
 */
@jakarta.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class SentimentScore {
  @JsonProperty("positive")
  private Double positive = null;

  @JsonProperty("negative")
  private Double negative = null;

  @JsonProperty("neutral")
  private Double neutral = null;

  @JsonProperty("mixed")
  private Double mixed = null;

  public SentimentScore positive(Double positive) {
    this.positive = positive;
    return this;
  }

   /**
   * Get positive
   * @return positive
  **/
  public Double getPositive() {
    return positive;
  }

  public void setPositive(Double positive) {
    this.positive = positive;
  }

  public SentimentScore negative(Double negative) {
    this.negative = negative;
    return this;
  }

   /**
   * Get negative
   * @return negative
  **/
  public Double getNegative() {
    return negative;
  }

  public void setNegative(Double negative) {
    this.negative = negative;
  }

  public SentimentScore neutral(Double neutral) {
    this.neutral = neutral;
    return this;
  }

   /**
   * Get neutral
   * @return neutral
  **/
  public Double getNeutral() {
    return neutral;
  }

  public void setNeutral(Double neutral) {
    this.neutral = neutral;
  }

  public SentimentScore mixed(Double mixed) {
    this.mixed = mixed;
    return this;
  }

   /**
   * Get mixed
   * @return mixed
  **/
  public Double getMixed() {
    return mixed;
  }

  public void setMixed(Double mixed) {
    this.mixed = mixed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentimentScore sentimentScore = (SentimentScore) o;
    return Objects.equals(this.positive, sentimentScore.positive) &&
        Objects.equals(this.negative, sentimentScore.negative) &&
        Objects.equals(this.neutral, sentimentScore.neutral) &&
        Objects.equals(this.mixed, sentimentScore.mixed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(positive, negative, neutral, mixed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentimentScore {\n");
    
    sb.append("    positive: ").append(toIndentedString(positive)).append("\n");
    sb.append("    negative: ").append(toIndentedString(negative)).append("\n");
    sb.append("    neutral: ").append(toIndentedString(neutral)).append("\n");
    sb.append("    mixed: ").append(toIndentedString(mixed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
