/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.SentimentScore;
import com.amazonaws.lex.runtime.v2.SentimentType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * &lt;p&gt;Provides information about the sentiment expressed in a user&#x27;s response in a conversation. Sentiments are determined using Amazon Comprehend. Sentiments are only returned if they are enabled for the bot.&lt;/p&gt; &lt;p&gt;For more information, see &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/comprehend/latest/dg/how-sentiment.html\&quot;&gt; Determine Sentiment &lt;/a&gt; in the &lt;i&gt;Amazon Comprehend developer guide&lt;/i&gt;.&lt;/p&gt;
 */
@jakarta.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class SentimentResponse {
  @JsonProperty("sentiment")
  private SentimentType sentiment = null;

  @JsonProperty("sentimentScore")
  private SentimentScore sentimentScore = null;

  public SentimentResponse sentiment(SentimentType sentiment) {
    this.sentiment = sentiment;
    return this;
  }

   /**
   * Get sentiment
   * @return sentiment
  **/
  public SentimentType getSentiment() {
    return sentiment;
  }

  public void setSentiment(SentimentType sentiment) {
    this.sentiment = sentiment;
  }

  public SentimentResponse sentimentScore(SentimentScore sentimentScore) {
    this.sentimentScore = sentimentScore;
    return this;
  }

   /**
   * Get sentimentScore
   * @return sentimentScore
  **/
  public SentimentScore getSentimentScore() {
    return sentimentScore;
  }

  public void setSentimentScore(SentimentScore sentimentScore) {
    this.sentimentScore = sentimentScore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentimentResponse sentimentResponse = (SentimentResponse) o;
    return Objects.equals(this.sentiment, sentimentResponse.sentiment) &&
        Objects.equals(this.sentimentScore, sentimentResponse.sentimentScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sentiment, sentimentScore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentimentResponse {\n");
    
    sb.append("    sentiment: ").append(toIndentedString(sentiment)).append("\n");
    sb.append("    sentimentScore: ").append(toIndentedString(sentimentScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
