/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.ActiveContextsList;
import com.amazonaws.lex.runtime.v2.DialogAction;
import com.amazonaws.lex.runtime.v2.Intent;
import com.amazonaws.lex.runtime.v2.StringMap;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The state of the user&#x27;s session with Amazon Lex V2.
 */
@jakarta.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class SessionState {
  @JsonProperty("dialogAction")
  private DialogAction dialogAction = null;

  @JsonProperty("intent")
  private Intent intent = null;

  @JsonProperty("activeContexts")
  private ActiveContextsList activeContexts = null;

  @JsonProperty("sessionAttributes")
  private StringMap sessionAttributes = null;

  @JsonProperty("originatingRequestId")
  private String originatingRequestId = null;

  public SessionState dialogAction(DialogAction dialogAction) {
    this.dialogAction = dialogAction;
    return this;
  }

   /**
   * Get dialogAction
   * @return dialogAction
  **/
  public DialogAction getDialogAction() {
    return dialogAction;
  }

  public void setDialogAction(DialogAction dialogAction) {
    this.dialogAction = dialogAction;
  }

  public SessionState intent(Intent intent) {
    this.intent = intent;
    return this;
  }

   /**
   * Get intent
   * @return intent
  **/
  public Intent getIntent() {
    return intent;
  }

  public void setIntent(Intent intent) {
    this.intent = intent;
  }

  public SessionState activeContexts(ActiveContextsList activeContexts) {
    this.activeContexts = activeContexts;
    return this;
  }

   /**
   * Get activeContexts
   * @return activeContexts
  **/
  public ActiveContextsList getActiveContexts() {
    return activeContexts;
  }

  public void setActiveContexts(ActiveContextsList activeContexts) {
    this.activeContexts = activeContexts;
  }

  public SessionState sessionAttributes(StringMap sessionAttributes) {
    this.sessionAttributes = sessionAttributes;
    return this;
  }

   /**
   * Get sessionAttributes
   * @return sessionAttributes
  **/
  public StringMap getSessionAttributes() {
    return sessionAttributes;
  }

  public void setSessionAttributes(StringMap sessionAttributes) {
    this.sessionAttributes = sessionAttributes;
  }

  public SessionState originatingRequestId(String originatingRequestId) {
    this.originatingRequestId = originatingRequestId;
    return this;
  }

   /**
   * Get originatingRequestId
   * @return originatingRequestId
  **/
  public String getOriginatingRequestId() {
    return originatingRequestId;
  }

  public void setOriginatingRequestId(String originatingRequestId) {
    this.originatingRequestId = originatingRequestId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionState sessionState = (SessionState) o;
    return Objects.equals(this.dialogAction, sessionState.dialogAction) &&
        Objects.equals(this.intent, sessionState.intent) &&
        Objects.equals(this.activeContexts, sessionState.activeContexts) &&
        Objects.equals(this.sessionAttributes, sessionState.sessionAttributes) &&
        Objects.equals(this.originatingRequestId, sessionState.originatingRequestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dialogAction, intent, activeContexts, sessionAttributes, originatingRequestId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionState {\n");
    
    sb.append("    dialogAction: ").append(toIndentedString(dialogAction)).append("\n");
    sb.append("    intent: ").append(toIndentedString(intent)).append("\n");
    sb.append("    activeContexts: ").append(toIndentedString(activeContexts)).append("\n");
    sb.append("    sessionAttributes: ").append(toIndentedString(sessionAttributes)).append("\n");
    sb.append("    originatingRequestId: ").append(toIndentedString(originatingRequestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
