/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState;
import com.amazonaws.lex.runtime.v2.Message;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * SessionsSessionIdBody
 */

@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class SessionsSessionIdBody {
  @JsonProperty("messages")
  private List<Message> messages = null;

  @JsonProperty("sessionState")
  private BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState sessionState = null;

  @JsonProperty("requestAttributes")
  private Map<String, String> requestAttributes = null;

  public SessionsSessionIdBody messages(List<Message> messages) {
    this.messages = messages;
    return this;
  }

  public SessionsSessionIdBody addMessagesItem(Message messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * A list of messages to send to the user. Messages are sent in the order that they are defined in the list.
   * @return messages
  **/
  public List<Message> getMessages() {
    return messages;
  }

  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }

  public SessionsSessionIdBody sessionState(BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState sessionState) {
    this.sessionState = sessionState;
    return this;
  }

   /**
   * Get sessionState
   * @return sessionState
  **/
  public BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState getSessionState() {
    return sessionState;
  }

  public void setSessionState(BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState sessionState) {
    this.sessionState = sessionState;
  }

  public SessionsSessionIdBody requestAttributes(Map<String, String> requestAttributes) {
    this.requestAttributes = requestAttributes;
    return this;
  }

  public SessionsSessionIdBody putRequestAttributesItem(String key, String requestAttributesItem) {
    if (this.requestAttributes == null) {
      this.requestAttributes = new HashMap<>();
    }
    this.requestAttributes.put(key, requestAttributesItem);
    return this;
  }

   /**
   * &lt;p&gt;Request-specific information passed between Amazon Lex V2 and the client application.&lt;/p&gt; &lt;p&gt;The namespace &lt;code&gt;x-amz-lex:&lt;/code&gt; is reserved for special attributes. Don&#x27;t create any request attributes with the prefix &lt;code&gt;x-amz-lex:&lt;/code&gt;.&lt;/p&gt;
   * @return requestAttributes
  **/
  public Map<String, String> getRequestAttributes() {
    return requestAttributes;
  }

  public void setRequestAttributes(Map<String, String> requestAttributes) {
    this.requestAttributes = requestAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionsSessionIdBody sessionsSessionIdBody = (SessionsSessionIdBody) o;
    return Objects.equals(this.messages, sessionsSessionIdBody.messages) &&
        Objects.equals(this.sessionState, sessionsSessionIdBody.sessionState) &&
        Objects.equals(this.requestAttributes, sessionsSessionIdBody.requestAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, sessionState, requestAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionsSessionIdBody {\n");
    
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    sessionState: ").append(toIndentedString(sessionState)).append("\n");
    sb.append("    requestAttributes: ").append(toIndentedString(requestAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
