/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * SessionIdTextBody
 */

@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class SessionIdTextBody {
  @JsonProperty("text")
  private String text = null;

  @JsonProperty("sessionState")
  private BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState sessionState = null;

  @JsonProperty("requestAttributes")
  private Map<String, String> requestAttributes = null;

  public SessionIdTextBody text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The text that the user entered. Amazon Lex V2 interprets this text.
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public SessionIdTextBody sessionState(BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState sessionState) {
    this.sessionState = sessionState;
    return this;
  }

   /**
   * Get sessionState
   * @return sessionState
  **/
  public BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState getSessionState() {
    return sessionState;
  }

  public void setSessionState(BotsbotIdbotAliasesbotAliasIdbotLocaleslocaleIdsessionssessionIdSessionState sessionState) {
    this.sessionState = sessionState;
  }

  public SessionIdTextBody requestAttributes(Map<String, String> requestAttributes) {
    this.requestAttributes = requestAttributes;
    return this;
  }

  public SessionIdTextBody putRequestAttributesItem(String key, String requestAttributesItem) {
    if (this.requestAttributes == null) {
      this.requestAttributes = new HashMap<>();
    }
    this.requestAttributes.put(key, requestAttributesItem);
    return this;
  }

   /**
   * &lt;p&gt;Request-specific information passed between the client application and Amazon Lex V2 &lt;/p&gt; &lt;p&gt;The namespace &lt;code&gt;x-amz-lex:&lt;/code&gt; is reserved for special attributes. Don&#x27;t create any request attributes with the prefix &lt;code&gt;x-amz-lex:&lt;/code&gt;.&lt;/p&gt;
   * @return requestAttributes
  **/
  public Map<String, String> getRequestAttributes() {
    return requestAttributes;
  }

  public void setRequestAttributes(Map<String, String> requestAttributes) {
    this.requestAttributes = requestAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionIdTextBody sessionIdTextBody = (SessionIdTextBody) o;
    return Objects.equals(this.text, sessionIdTextBody.text) &&
        Objects.equals(this.sessionState, sessionIdTextBody.sessionState) &&
        Objects.equals(this.requestAttributes, sessionIdTextBody.requestAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, sessionState, requestAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionIdTextBody {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    sessionState: ").append(toIndentedString(sessionState)).append("\n");
    sb.append("    requestAttributes: ").append(toIndentedString(requestAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
