/*
 * Amazon Lex Runtime V2
 * <p/>
 *
 * OpenAPI spec version: 2020-08-07
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazonaws.lex.runtime.v2;

import java.util.Objects;
import java.util.Arrays;
import com.amazonaws.lex.runtime.v2.StringList;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The value of a slot.
 */
@javax.annotation.Generated(value = "ch.ivyteam.ivy.jaxrs.client.openapi.codegen.OpenApiCodegen$1", date = "2021-08-19T08:34:06.422757+02:00[Europe/Zurich]")
public class Value {
  @JsonProperty("originalValue")
  private String originalValue = null;

  @JsonProperty("interpretedValue")
  private String interpretedValue = null;

  @JsonProperty("resolvedValues")
  private StringList resolvedValues = null;

  public Value originalValue(String originalValue) {
    this.originalValue = originalValue;
    return this;
  }

   /**
   * Get originalValue
   * @return originalValue
  **/
  public String getOriginalValue() {
    return originalValue;
  }

  public void setOriginalValue(String originalValue) {
    this.originalValue = originalValue;
  }

  public Value interpretedValue(String interpretedValue) {
    this.interpretedValue = interpretedValue;
    return this;
  }

   /**
   * Get interpretedValue
   * @return interpretedValue
  **/
  public String getInterpretedValue() {
    return interpretedValue;
  }

  public void setInterpretedValue(String interpretedValue) {
    this.interpretedValue = interpretedValue;
  }

  public Value resolvedValues(StringList resolvedValues) {
    this.resolvedValues = resolvedValues;
    return this;
  }

   /**
   * Get resolvedValues
   * @return resolvedValues
  **/
  public StringList getResolvedValues() {
    return resolvedValues;
  }

  public void setResolvedValues(StringList resolvedValues) {
    this.resolvedValues = resolvedValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Value value = (Value) o;
    return Objects.equals(this.originalValue, value.originalValue) &&
        Objects.equals(this.interpretedValue, value.interpretedValue) &&
        Objects.equals(this.resolvedValues, value.resolvedValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalValue, interpretedValue, resolvedValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Value {\n");
    
    sb.append("    originalValue: ").append(toIndentedString(originalValue)).append("\n");
    sb.append("    interpretedValue: ").append(toIndentedString(interpretedValue)).append("\n");
    sb.append("    resolvedValues: ").append(toIndentedString(resolvedValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
