name: CI-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v2
    secrets:
      mvnArgs: -Daws.access.key=${{ secrets.AWS_ACCESS_KEY }} -Daws.secret.key=${{ secrets.AWS_SECRET_KEY }}
